name: Portainer CE
slug: hass-portainer
version: "2025.07.00"
description: "Portainer CE for container management on Home Assistant OS"
url: https://github.com/alvinchen1/hassio-addons/tree/main/hass-portainer
arch:
  - amd64
  - aarch64
startup: services
init: false
stage: stable

panel_icon: mdi:docker
panel_title: Portainer
webui: http://[HOST]:[PORT:9000]

ports:
  9000/tcp: 9000

options: {}
schema: {}